# ---------- build ----------
FROM node:20-alpine AS build
WORKDIR /app

COPY src/main/front/package*.json ./
RUN npm ci
COPY src/main/front/ ./

# 프론트는 /api 로 빌드
ARG REACT_APP_API_BASE=/api
ENV REACT_APP_API_BASE=${REACT_APP_API_BASE}

RUN npm run build

# ---------- run ----------
FROM nginx:1.25-alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx","-g","daemon off;"]
