name: Build & Push (Docker Hub) & Update GitOps

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

env:
  IMAGE_BACKEND: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/lunch-backend
  IMAGE_FRONTEND: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/lunch-frontend
  GITOPS_REPO: ${{ secrets.GITOPS_REPO }}
  KUSTOMIZE_PATH: base

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push backend
        run: |
          docker build -f Dockerfile.backend -t $IMAGE_BACKEND:${{ github.sha }} .
          docker tag  $IMAGE_BACKEND:${{ github.sha }} $IMAGE_BACKEND:latest
          docker push $IMAGE_BACKEND:${{ github.sha }}
          docker push $IMAGE_BACKEND:latest

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push frontend
        run: |
          docker build -f Dockerfile.frontend \
            --build-arg REACT_APP_API_BASE="${{ secrets.REACT_APP_API_BASE || '/api' }}" \
            -t $IMAGE_FRONTEND:${{ github.sha }} .
          docker tag  $IMAGE_FRONTEND:${{ github.sha }} $IMAGE_FRONTEND:latest
          docker push $IMAGE_FRONTEND:${{ github.sha }}
          docker push $IMAGE_FRONTEND:latest

  update-gitops:
    needs: [ build-backend, build-frontend ]
    runs-on: ubuntu-latest
    steps:
      - name: Clone gitops repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GITOPS_REPO }}
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops

      - name: Install yq
        run: sudo snap install yq

      - name: Update image tags in kustomization.yaml
        env:
          IMAGE_BACKEND: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/lunch-backend
          IMAGE_FRONTEND: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/lunch-frontend
          GITHUB_SHA: ${{ github.sha }}
        run: |
          cd gitops/${{ env.KUSTOMIZE_PATH }}

          # backend 이미지 업데이트
          yq -i '
            .images[] |= 
              (if .name == strenv(IMAGE_BACKEND) then .newTag = strenv(GITHUB_SHA) else . end)
          ' kustomization.yaml

          # frontend 이미지 업데이트
          yq -i '
            .images[] |= 
              (if .name == strenv(IMAGE_FRONTEND) then .newTag = strenv(GITHUB_SHA) else . end)
          ' kustomization.yaml

      - name: Commit & push
        run: |
          cd gitops
          git config user.name "YangjiwooGN"
          git config user.email "jwoo3460@gmail.com"
          git add -A
          git commit -m "Update images to $GITHUB_SHA" || echo "No changes"
          git push